- name: install appropriate RPMs
  yum: name="{{item}}" state=present
  with_items:
  - perl-DBI
  - perl-DBD-Pg
  - perl-DBD-MySQL
  - perl-JSON
  - perl-File-Slurp
  - perl-Time-HiRes
  - strace

- name: install runquery.pl
  copy: src=runquery.pl dest="{{homedir}}/runquery.pl"

- name: install data.json
  copy: src=data.json dest="{{homedir}}/data.json"

- name: install mysql config file
  template: src=mysqlconfig.j2 dest="{{homedir}}/mysqlconfig"
  when: 'db_driver == "MySQL" or db_driver == "both"'

- name: install pg config file
  template: src=pgconfig.j2 dest="{{homedir}}/pgconfig"
  when: 'db_driver == "Pg" or db_driver == "both"'
