- name: install appropriate RPMs
  yum: name="{{item}}" state=present
  with_items:
  - perl-DBI
  - perl-DBD-Pg
  - perl-DBD-MySQL
  - perl-JSON
  - perl-File-Slurp
  - perl-Time-HiRes
  - strace

- name: install runquery.pl
  copy: src=runquery.pl dest="{{homedir}}/runquery.pl"

- name: install data.json
  copy: src=data.json dest="{{homedir}}/data.json"

- name: install configuration files
  template: src=config.j2 dest="{{homedir}}/{{item.db_driver|lower}}-{{item.db_version}}-config"
  with_items: database_configs
